---
##
## RedHat Repository for Jenkins
## https://pkg.jenkins.io/redhat-stable/
##
## Linux Software Repositories - Google
## https://www.google.com/linuxrepositories/
##
## AdditionalResources/Repositories/GoogleYumRepos - CentOS Wiki
## https://wiki.centos.org/AdditionalResources/Repositories/GoogleYumRepos
##

# tasks file for setup-jenkins
- name: Download the Jenkins repository file
  become: True
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0644
    owner: root
    group: root
    seuser: system_u
    serole: object_r
    setype: system_conf_t
    selevel: s0

- name: Import a gpg key for the Jenkins repository
  become: True
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Add the Google repository
  become: True
  yum_repository:
    name: google
    description: Google - $basearch
    baseurl: http://dl.google.com/linux/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey:
      - https://dl.google.com/linux/linux_signing_key.pub

- name: Install packages
  become: True
  package:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - "@development"
    - unzip
    - java-1.8.0-openjdk-devel
    - xorg-x11-server-Xvfb
    - firefox
    - google-chrome-stable
    - jenkins

- name: Check the latest version of chromedriver
  uri:
    url: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
    return_content: yes
  register: chromedriver_version
  
- name: Install chromedriver
  become: True
  unarchive:
    src: "https://chromedriver.storage.googleapis.com/{{ chromedriver_version.content }}/chromedriver_linux64.zip"
    dest: /usr/local/bin
    remote_src: yes

- name: Enable and start Jenkins
  become: True
  systemd:
    name: jenkins
    enabled: yes
    state: started
